version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app


  db:
    image: postgres:16
    container_name: postgres_street_app
    env_file:
      - .env
    depends_on:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6
    container_name: redis_cache
    depends_on:
      - app
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data: